if(NOT DEFINED SOURCE_DIR OR NOT IS_DIRECTORY "${SOURCE_DIR}")
    message(FATAL_ERROR "Runtime content source directory is missing: ${SOURCE_DIR}")
endif()
if(NOT DEFINED DESTINATION_DIR OR DESTINATION_DIR STREQUAL "")
    message(FATAL_ERROR "Runtime content destination directory was not provided")
endif()
if(NOT DEFINED MANIFEST_PATH OR MANIFEST_PATH STREQUAL "")
    message(FATAL_ERROR "Runtime content manifest path was not provided")
endif()

file(MAKE_DIRECTORY "${DESTINATION_DIR}")
file(GLOB_RECURSE CONTENT_FILES LIST_DIRECTORIES false "${SOURCE_DIR}/*")

set(PREVIOUS_ENTRIES)
set(HAVE_MANIFEST FALSE)
if(EXISTS "${MANIFEST_PATH}")
    file(STRINGS "${MANIFEST_PATH}" PREVIOUS_ENTRIES)
    set(HAVE_MANIFEST TRUE)
endif()

set(CURRENT_ENTRIES)
set(COPIED_COUNT 0)
foreach(SOURCE_FILE IN LISTS CONTENT_FILES)
    file(RELATIVE_PATH RELATIVE_FILE "${SOURCE_DIR}" "${SOURCE_FILE}")
    file(SIZE "${SOURCE_FILE}" SOURCE_SIZE)
    file(TIMESTAMP "${SOURCE_FILE}" SOURCE_TIMESTAMP "%Y%m%d%H%M%S" UTC)
    set(CURRENT_ENTRY "${RELATIVE_FILE}|${SOURCE_SIZE}|${SOURCE_TIMESTAMP}")
    list(APPEND CURRENT_ENTRIES "${CURRENT_ENTRY}")

    set(DESTINATION_FILE "${DESTINATION_DIR}/${RELATIVE_FILE}")
    set(SHOULD_COPY FALSE)
    if(NOT EXISTS "${DESTINATION_FILE}")
        set(SHOULD_COPY TRUE)
    elseif(HAVE_MANIFEST)
        list(FIND PREVIOUS_ENTRIES "${CURRENT_ENTRY}" ENTRY_INDEX)
        if(ENTRY_INDEX EQUAL -1)
            set(SHOULD_COPY TRUE)
        endif()
    else()
        # Bootstrap an existing build tree without hashing every multi-GiB
        # asset. A different size still identifies an incomplete stale copy.
        file(SIZE "${DESTINATION_FILE}" DESTINATION_SIZE)
        if(NOT SOURCE_SIZE EQUAL DESTINATION_SIZE)
            set(SHOULD_COPY TRUE)
        endif()
    endif()

    if(SHOULD_COPY)
        get_filename_component(DESTINATION_PARENT "${DESTINATION_FILE}" DIRECTORY)
        file(MAKE_DIRECTORY "${DESTINATION_PARENT}")
        file(COPY_FILE "${SOURCE_FILE}" "${DESTINATION_FILE}" ONLY_IF_DIFFERENT)
        math(EXPR COPIED_COUNT "${COPIED_COUNT} + 1")
    endif()
endforeach()

list(JOIN CURRENT_ENTRIES "\n" MANIFEST_CONTENT)
file(WRITE "${MANIFEST_PATH}" "${MANIFEST_CONTENT}\n")
message(STATUS "Runtime content checked: ${COPIED_COUNT} file(s) updated")
