#pragma once

#include <DirectXMath.h>
#include <array>
#include <algorithm>
#include <cmath>

struct OceanWave {
    DirectX::XMFLOAT2 direction = { 1.0f, 0.0f };
    float amplitude = 0.1f;
    float wavelength = 10.0f;
    float steepness = 0.2f;
};

struct OceanWaveSettings {
    static constexpr size_t WaveCount = 8;
    std::array<OceanWave, WaveCount> waves = {};
    DirectX::XMFLOAT3 absorption = { 0.45f, 0.16f, 0.09f };
    DirectX::XMFLOAT3 shallowScatter = { 0.015f, 0.14f, 0.16f };
    DirectX::XMFLOAT3 deepScatter = { 0.004f, 0.052f, 0.10f };
    float microNormalStrength = 0.055f;
    float foamDepth = 0.72f;
    float foamCrest = 0.18f;

    // Live High-path sliders, applied on top of the authored spectrum above.
    // They live here rather than only in Scene so the CPU buoyancy query and
    // the GPU surface scale by the same numbers: the renderer folds these into
    // the uploaded wave constants, and EvaluateHeightAndSlope applies them
    // directly. A slider that moved only one of the two would float boats above
    // or below the water being drawn.
    float heightScale = 1.0f;
    float lengthScale = 1.0f;
    float speedScale = 1.0f;

    static OceanWaveSettings CalmTropical() {
        OceanWaveSettings result;
        // A directional sea, not a confused one. Every train sits within a
        // spread either side of one dominant swell bearing (+20 degrees), the
        // way a real ocean arrives: generated by weather far away, so the long
        // components come in nearly aligned and only the short, locally-driven
        // chop wanders off-axis.
        //
        // The previous set spanned 310 degrees, which is what a harbour chop
        // looks like, not a swell -- and it left several trains heading out to
        // sea, so the near-shore refraction had nothing sensible to bend and
        // just pinned them sideways. Here every bearing lies within 56 degrees
        // of the others, clustered on a dominant heading, and the spread is
        // wide enough that neighbouring periods still cross rather than
        // reinforcing into one ridge.
        //
        // Periods fill the geometric progression without repeats, and
        // amplitudes follow the same falloff, keeping summed steepness well
        // under the Gerstner loop threshold (see the renderer's maxSteepness
        // clamp).
        result.waves = {{
            // Long swell. The two dominant trains are deliberately 26 degrees
            // apart: aligning them stretched their interference beat to 66 m,
            // and a strong long beat between the two biggest amplitudes reads
            // as a regular field of blobs tiling the surface. 26 degrees pulls
            // it back to 46 m, under the 41 m the old wide spectrum ran at.
            {{  0.829f,   0.559f }, 0.130f,  31.0f, 0.21f},  //  +34 deg
            {{  0.990f,   0.139f }, 0.180f,  22.0f, 0.24f},  //   +8 deg
            {{  0.927f,   0.375f }, 0.115f,  15.0f, 0.20f},  //  +22 deg
            {{  0.998f,  -0.070f }, 0.100f,  11.0f, 0.20f},  //   -4 deg
            // mid chop: wider off-axis
            {{  0.766f,   0.643f }, 0.068f,   7.0f, 0.18f},  //  +40 deg
            {{  0.970f,  -0.242f }, 0.045f,   4.5f, 0.16f},  //  -14 deg
            // short chop: widest, locally driven
            {{  0.616f,   0.788f }, 0.028f,   2.8f, 0.13f},  //  +52 deg
            {{  0.899f,  -0.438f }, 0.018f,   1.8f, 0.10f}   //  -26 deg
        }};
        return result;
    }

    // Linear directional waves, as the High path has always used: each
    // component sweeps across the world on its authored bearing. Bathymetric
    // refraction and shoaling live in the Ultra path, which has real bed data
    // to drive them; approximating either here made the surface worse, not
    // better. The slider scales are applied so buoyancy tracks the drawn
    // surface exactly.
    float EvaluateHeightAndSlope(float x, float z, float time,
                                 float& dhdx, float& dhdz) const {
        constexpr float gravity = 9.81f;
        dhdx = 0.0f;
        dhdz = 0.0f;
        float height = 0.0f;
        const float safeHeight = (std::max)(0.0f, heightScale);
        const float safeLength = (std::max)(0.05f, lengthScale);
        const float scaledTime = time * speedScale;
        for (const OceanWave& wave : waves) {
            const float dirLength = std::sqrt(
                wave.direction.x * wave.direction.x +
                wave.direction.y * wave.direction.y);
            const float invLength = dirLength > 1e-5f ? 1.0f / dirLength : 0.0f;
            const float dx = wave.direction.x * invLength;
            const float dz = wave.direction.y * invLength;
            const float wavelength =
                (std::max)(wave.wavelength * safeLength, 0.1f);
            const float amplitude = wave.amplitude * safeHeight;
            const float k = DirectX::XM_2PI / wavelength;
            const float omega = std::sqrt(gravity * k);
            const float phase = k * (dx * x + dz * z) - omega * scaledTime;
            const float sine = std::sin(phase);
            const float cosine = std::cos(phase);
            height += amplitude * sine;
            const float derivative = amplitude * k * cosine;
            dhdx += derivative * dx;
            dhdz += derivative * dz;
        }
        return height;
    }
};
